name: CI/CD Laravel + Vue - Staging/Prod

on:
  push:
    branches:
      - main
      - develop

jobs:
  laravel-tests:
    name: Testes Laravel
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: laravel
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Instalar dependências do Laravel
        run: |
          cd back-end
          composer install --no-progress
          cp .env.example .env
          php artisan key:generate
          php artisan migrate --force
        env:
          DB_CONNECTION: pgsql
          DB_HOST: 127.0.0.1
          DB_PORT: 5432
          DB_DATABASE: laravel
          DB_USERNAME: postgres
          DB_PASSWORD: password

      - name: Rodar testes
        run: |
          cd backend
          ./vendor/bin/phpunit

  vue-tests:
    name: Testes Vue
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Rodar testes frontend
        run: |
          cd front-end
          npm install
          npm run test

  deploy:
    name: Deploy AWS
    needs: [laravel-tests, vue-tests]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy para AWS via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ github.ref == 'refs/heads/main' && secrets.AWS_PROD_HOST || secrets.AWS_STAGING_HOST }}
          username: ${{ github.ref == 'refs/heads/main' && secrets.AWS_PROD_USER || secrets.AWS_STAGING_USER }}
          key: ${{ github.ref == 'refs/heads/main' && secrets.AWS_PROD_SSH_KEY || secrets.AWS_STAGING_SSH_KEY }}
          script: |
            echo "🔄 Iniciando deploy na AWS..."
            if [ "${{ github.ref }}" == "refs/heads/main" ]; then
              cd /var/www/producao-backend
            else
              cd /var/www/staging-backend
            fi
            git pull origin ${{ github.ref_name }}
            composer install --no-dev
            php artisan migrate --force
            php artisan config:cache

            echo "➡️ Deploy Frontend"
            if [ "${{ github.ref }}" == "refs/heads/main" ]; then
              cd /var/www/producao-frontend
            else
              cd /var/www/staging-frontend
            fi
            git pull origin ${{ github.ref_name }}
            npm install
            npm run build
