name: CI/CD Laravel + Vue - Staging/Prod

on:
  push:
    branches:
      - main
      - develop

jobs:
  laravel-tests:
    name: Testes Laravel
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: laravel
        ports:
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Instalar dependências do Laravel
        run: |
          cd back-end
          composer install --no-progress
          cp .env.example .env
          php artisan key:generate
          php artisan migrate --force
        env:
          DB_CONNECTION: pgsql
          DB_HOST: 127.0.0.1
          DB_PORT: 5432
          DB_DATABASE: laravel
          DB_USERNAME: postgres
          DB_PASSWORD: password

      - name: Rodar testes
        run: |
          cd back-end
          ./vendor/bin/phpunit

  vue-tests:
    name: Testes Vue
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Rodar testes front-end
        run: |
          cd front-end
          npm install
          npm run test

  deploy:
    name: Deploy AWS com Ansible
    needs: [laravel-tests, vue-tests]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Instalar Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Dar permissão à chave PEM
        run: chmod 600 ansible/clinica-key.pem

      - name: Configurar inventário do Ansible
        run: |
          echo "[frontend]" > ansible/inventory.ini
          echo "frontend ansible_host=${{ github.ref == 'refs/heads/main' && secrets.ANSIBLE_PROD_FRONTEND_HOST || secrets.ANSIBLE_STAGING_FRONTEND_HOST }} ansible_user=ubuntu ansible_ssh_private_key_file=ansible/clinica-key.pem" >> ansible/inventory.ini
          echo "[backend]" >> ansible/inventory.ini
          echo "backend ansible_host=${{ github.ref == 'refs/heads/main' && secrets.ANSIBLE_PROD_BACKEND_HOST || secrets.ANSIBLE_STAGING_BACKEND_HOST }} ansible_user=ubuntu ansible_ssh_private_key_file=ansible/clinica-key.pem" >> ansible/inventory.ini

      - name: Rodar playbook do Ansible
        run: |
          ansible-playbook -i ansible/inventory.ini ansible/deploy.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"

